version: "3.7"

services:
  php:
    image: arm64v8/php:8.1.25-apache-bullseye
    ports:
      - 80:80
    volumes:
      - ./aws_credentials:/.aws
      - ./src:/var/www/html

  composer:
    image: composer:1.9
    command: ["composer", "install"]
    volumes:
      - ./src:/app
